name: artbeat_admin
description: "ARTbeat administrator module"
version: 0.0.1
homepage: https://github.com/kristybock/artbeat

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  artbeat_core:
    path: ../artbeat_core
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  firebase_storage: ^12.4.7
  provider: ^6.1.1
  flutter_secure_storage: ^9.0.0
  jwt_decoder: ^2.0.1
  uuid: ^4.2.1

flutter:
  uses-material-design: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
