name: artbeat_settings
description: Settings module for ARTbeat application
version: 0.0.2
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter

  # Core dependencies
  artbeat_core:
    path: ../artbeat_core
  artbeat_artist:
    path: ../artbeat_artist

  # Firebase dependencies - match main project versions
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  firebase_storage: ^12.4.7
  firebase_analytics: ^11.5.0
  firebase_app_check: ^0.3.2+7

  # Utilities
  provider: ^6.0.5

flutter:
  uses-material-design: true
  assets:
    - assets/default_profile.png

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.9
  shared_preferences: ^2.2.2
