name: artbeat
description: ARTbeat - Discover and share art in your community.
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  firebase_storage: ^12.4.6
  firebase_app_check: ^0.3.2+6
  image_picker: ^1.0.0
  flutter_svg: ^2.0.7
  intl: ^0.20.2
  flutter_spinkit: ^5.2.0
  provider: ^6.0.5
  uuid: ^4.5.1
  cached_network_image: ^3.2.3
  google_fonts: ^6.2.1
  carousel_slider: ^5.0.0
  flutter_staggered_grid_view: ^0.7.0
  url_launcher: ^6.1.12
  geolocator: ^14.0.0
  geocoding: ^3.0.0
  location: ^8.0.0
  flutter_local_notifications: ^19.2.0
  table_calendar: ^3.0.9
  share_plus: ^11.0.0
  path_provider: ^2.0.15
  shimmer: ^3.0.0
  flutter_launcher_icons: ^0.14.3
  permission_handler: ^12.0.0+1
  rxdart: ^0.28.0
  flutter_image_compress: ^2.0.3
  shared_preferences: ^2.2.0
  connectivity_plus: ^6.1.4
  video_player: ^2.7.0
  file_picker: ^10.1.9
  flutter_cache_manager: ^3.3.1
  timeago: ^3.5.0
  dotted_border: ^3.0.1
  flutter_stripe: ^11.5.0  # For Stripe payment integration
  http: ^1.1.0  # For API calls to backend
  fl_chart: ^1.0.0  # For analytics charts and graphs
  flutter_dotenv: ^5.1.0  # For managing environment variables
  logger: ^2.5.0
  google_maps_flutter: ^2.12.2
  vector_math: ^2.1.4  # For math calculations

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.8
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/ # Add this line to include all images in the folder
    - assets/default_profile.png
    - assets/event_placeholder.png
    - assets/event_placeholder.svg
    - assets/triangle.png
    - .env
    - .env.example