name: artbeat
description: ARTbeat application for artists and art enthusiasts

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`.
# To see which dependencies have newer versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.5
  
  # Firebase dependencies - align with packages
  firebase_core: ^2.24.2  # Base version
  firebase_auth: ^4.15.3  # Compatible with firebase_core 2.24.2
  cloud_firestore: ^4.13.6  # Compatible with firebase_core 2.24.2
  firebase_storage: ^11.5.6  # Compatible with firebase_core 2.24.2
  firebase_app_check: ^0.2.1+8  # Compatible with firebase_core 2.24.2
  
  # Camera and image handling
  camera: ^0.10.6  # Updated version
  image_picker: ^1.0.4  # Updated version
  
  # File system and storage
  path_provider: ^2.1.5
  path: ^1.9.1
  
  # Geolocation and device info
  geocoding: ^2.2.0  # Updated for compatibility
  device_info_plus: ^10.1.2
  connectivity_plus: ^6.1.4
  package_info_plus: ^8.3.0
  geolocator: ^11.0.0  # Updated for compatibility
  
  # Google Maps and ML Kit
  google_maps_flutter: ^2.5.3
  google_mlkit_text_recognition: ^0.11.0
  
  # Networking and sharing
  http: ^1.2.0
  share_plus: ^7.2.1
  url_launcher: ^6.2.4
  
  # Local storage and caching
  sqflite: ^2.3.2
  flutter_cache_manager: ^3.3.1
  
  # Math and utilities
  vector_math: ^2.1.4  # Required for Matrix4 operations
  provider: ^6.1.1
  intl: ^0.19.0  # Updated to latest version

  # Local packages
  artbeat_core:
    path: packages/artbeat_core
  artbeat_auth:
    path: packages/artbeat_auth
  artbeat_profile:
    path: packages/artbeat_profile
  artbeat_artist:
    path: packages/artbeat_artist
  artbeat_artwork:
    path: packages/artbeat_artwork
  artbeat_art_walk:
    path: packages/artbeat_art_walk
  artbeat_community:
    path: packages/artbeat_community
  artbeat_settings:
    path: packages/artbeat_settings
  artbeat_capture:
    path: packages/artbeat_capture

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.8
  fake_async: ^1.3.1
  
  # Development helpers
  flutter_lints: ^3.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/artbeat_logo.png
    - assets/default_profile.png
    - assets/event_placeholder.png
    - assets/event_placeholder.svg
    - assets/triangle.png
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - test_resources/
    - test_resources/test_image.jpg

  # Font configuration
  fonts:
    - family: FallingSky
      fonts:
        - asset: assets/fonts/FallingSky.otf
        - asset: assets/fonts/FallingSkyBd.otf
          weight: 700
        - asset: assets/fonts/FallingSkyCond.otf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
