name: artbeat
description: "ARTbeat - A modular Flutter application for artists, galleries, and art lovers."
publish_to: "none"

version: 1.1.0+33

environment:
  sdk: "^3.8.0"
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter

  # Local modules
  artbeat_admin:
    path: packages/artbeat_admin
  artbeat_ads:
    path: packages/artbeat_ads
  artbeat_art_walk:
    path: packages/artbeat_art_walk
  artbeat_artist:
    path: packages/artbeat_artist
  artbeat_artwork:
    path: packages/artbeat_artwork
  artbeat_auth:
    path: packages/artbeat_auth
  artbeat_community:
    path: packages/artbeat_community
  artbeat_core:
    path: packages/artbeat_core
  artbeat_messaging:
    path: packages/artbeat_messaging
  artbeat_profile:
    path: packages/artbeat_profile
  artbeat_settings:
    path: packages/artbeat_settings
  artbeat_capture:
    path: packages/artbeat_capture
  artbeat_events:
    path: packages/artbeat_events

  # Firebase
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  firebase_storage: ^12.4.7
  firebase_analytics: ^11.5.0
  firebase_app_check: ^0.3.2+7
  firebase_messaging: ^15.2.7
  firebase_data_connect: ^0.1.5+1 # Added for Data Connect support

  # Permissions
  permission_handler: ^12.0.1

  # UI packages
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0
  # Optimized image caching with buffer management
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  google_maps_flutter: ^2.5.3

  # Utils
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  path_provider: ^2.1.5
  http: ^1.4.0
  geocoding: ^4.0.0
  camera: ^0.11.1
  device_info_plus: ^11.5.0
  package_info_plus: ^8.2.0
  image_picker: ^1.0.0
  image_cropper: ^9.1.0
  geolocator: ^14.0.1
  flutter_local_notifications: ^18.0.1

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/default_artwork.png
    - assets/default_profile.png
    - assets/event_placeholder.png
    - assets/event_placeholder.svg
    - assets/logo.png
    - assets/triangle.png
    - assets/images/subtle_pattern.png
    - assets/artist_onboarding_hero.png
    - .env

  # Fonts
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
    - family: Limelight
      fonts:
        - asset: assets/fonts/Limelight/Limelight-Regular.ttf

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.10
  integration_test:
    sdk: flutter
  firebase_auth_platform_interface: any
