# ARTbeat Test Configuration
# This file defines the testing strategy and configurations for all packages

test_config:
  # Global test settings
  timeout: 30s
  concurrency: 4
  coverage_threshold: 80

  # Test categories
  categories:
    unit:
      description: "Unit tests for individual functions and classes"
      timeout: 10s

    integration:
      description: "Integration tests for package interactions"
      timeout: 30s

    widget:
      description: "Widget tests for UI components"
      timeout: 20s

    end_to_end:
      description: "End-to-end tests for complete user flows"
      timeout: 60s

  # Package-specific configurations
  packages:
    artbeat_core:
      priority: high
      test_paths:
        - "packages/artbeat_core/test/"
      required_coverage: 85
      critical: true

    artbeat_auth:
      priority: high
      test_paths:
        - "packages/artbeat_auth/test/"
      required_coverage: 85
      critical: true

    artbeat_profile:
      priority: medium
      test_paths:
        - "packages/artbeat_profile/test/"
      required_coverage: 80

    artbeat_artwork:
      priority: medium
      test_paths:
        - "packages/artbeat_artwork/test/"
      required_coverage: 80

    artbeat_art_walk:
      priority: medium
      test_paths:
        - "packages/artbeat_art_walk/test/"
      required_coverage: 75

    artbeat_artist:
      priority: medium
      test_paths:
        - "packages/artbeat_artist/test/"
      required_coverage: 75

    artbeat_messaging:
      priority: medium
      test_paths:
        - "packages/artbeat_messaging/test/"
      required_coverage: 80

    artbeat_events:
      priority: medium
      test_paths:
        - "packages/artbeat_events/test/"
      required_coverage: 75

    artbeat_community:
      priority: medium
      test_paths:
        - "packages/artbeat_community/test/"
      required_coverage: 75

    artbeat_capture:
      priority: low
      test_paths:
        - "packages/artbeat_capture/test/"
      required_coverage: 70

    artbeat_settings:
      priority: low
      test_paths:
        - "packages/artbeat_settings/test/"
      required_coverage: 70

  # Integration test configurations
  integration_tests:
    - name: "Package Integration"
      path: "test/integration/package_integration_test.dart"
      dependencies: ["artbeat_core", "artbeat_auth", "artbeat_profile"]

    - name: "Auth Flow"
      path: "test/integration/auth_flow_test.dart"
      dependencies: ["artbeat_core", "artbeat_auth"]

    - name: "Artwork Management"
      path: "test/integration/artwork_management_test.dart"
      dependencies: ["artbeat_core", "artbeat_artwork", "artbeat_profile"]

  # Mock configurations
  mocks:
    firebase:
      - FirebaseAuth
      - FirebaseFirestore
      - FirebaseStorage
      - FirebaseAnalytics

    services:
      - AuthService
      - UserService
      - NavigationService
      - ConnectivityService

    external:
      - http.Client
      - SharedPreferences
      - Location

  # Test data configurations
  test_data:
    users:
      - uid: "test-user-1"
        email: "test@example.com"
        name: "Test User"
        type: "user"

      - uid: "test-artist-1"
        email: "artist@example.com"
        name: "Test Artist"
        type: "artist"

    artworks:
      - id: "test-artwork-1"
        title: "Test Artwork"
        artist_id: "test-artist-1"
        category: "painting"

    events:
      - id: "test-event-1"
        title: "Test Event"
        organizer_id: "test-artist-1"
        category: "exhibition"

# CI/CD specific settings
ci_config:
  flutter_version: "3.32.0"
  dart_version: "3.8.0"

  test_stages:
    - name: "Lint"
      command: "flutter analyze"

    - name: "Format Check"
      command: "dart format --set-exit-if-changed ."

    - name: "Unit Tests"
      command: "flutter test"

    - name: "Integration Tests"
      command: "flutter test test/integration/"

    - name: "Coverage"
      command: "flutter test --coverage"

  failure_conditions:
    - "Coverage below threshold"
    - "Lint errors present"
    - "Format issues present"
    - "Any test failure"

# Development workflow
dev_workflow:
  pre_commit:
    - "flutter analyze"
    - "dart format ."
    - "flutter test --no-coverage"

  pre_push:
    - "flutter test --coverage"
    - "Check coverage threshold"

  pre_release:
    - "Full test suite"
    - "Integration tests"
    - "Performance tests"
