name: artbeat_community
description: Social and community features for ARTbeat app
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  artbeat_core:
    path: ../artbeat_core
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  firebase_storage: ^11.7.7
  image_picker: ^1.0.4
  cached_network_image: ^3.2.3
  timeago: ^3.4.0
  intl: ^0.19.0
  artbeat_artist:
    path: ../artbeat_artist

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
