name: artbeat_community
description: Social and community features for ARTbeat app
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  artbeat_core:
    path: ../artbeat_core
  firebase_core: ^2.32.0
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  firebase_storage: ^11.7.7
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  timeago: ^3.4.0
  intl: ^0.19.0
  provider: ^6.0.5
  artbeat_artist:
    path: ../artbeat_artist
  share_plus: ^7.2.1
  google_maps_flutter: ^2.6.0
  flutter_svg: ^2.0.10+1
  profanity_filter: ^2.0.0
  url_launcher: ^6.2.5
  flutter_stripe: ^11.1.0
  uuid: ^4.1.0
  geolocator: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  mockito: ^5.4.4
  fake_cloud_firestore: ^2.4.5
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
