name: artbeat_events
description: Event management package for ARTbeat - handles event creation, ticketing, and management
version: 1.0.1
publish_to: none # This package is not intended for publishing

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase dependencies
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0

  # Stripe integration for paid tickets
  flutter_stripe: ^11.1.0

  # Notifications
  flutter_local_notifications: ^18.0.1
  awesome_notifications: ^0.10.1

  # Calendar integration
  device_calendar: ^4.3.2

  # Image handling
  image_picker: ^1.0.7
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1

  # Date/time handling
  intl: ^0.20.2
  timezone: ^0.9.4

  # Chart visualization for analytics
  fl_chart: ^0.69.0

  # HTTP requests
  http: ^1.2.0

  # State management
  provider: ^6.1.1

  # Logging
  logger: ^2.4.0

  # Local packages
  artbeat_core:
    path: ../artbeat_core
  artbeat_auth:
    path: ../artbeat_auth
  artbeat_ads:
    path: ../artbeat_ads

  # QR Code generation
  qr_flutter: ^4.1.0

  # Other dependencies
  uuid: ^4.3.3
  share_plus: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.9

  cloud_firestore_platform_interface: any
flutter:
  uses-material-design: true
