name: artbeat_events
description: Event management package for ARTbeat - handles event creation, ticketing, and management
version: 1.0.0
publish_to: none  # This package is not intended for publishing

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase dependencies
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  firebase_storage: ^12.4.7

  # Stripe integration for paid tickets
  flutter_stripe: ^11.1.0

  # Notifications
  flutter_local_notifications: ^18.0.1
  awesome_notifications: ^0.10.1

  # Calendar integration
  add_2_calendar: ^3.0.1

  # Image handling
  image_picker: ^1.0.7

  # Date/time handling
  intl: ^0.20.2

  # HTTP requests
  http: ^1.2.0

  # State management
  provider: ^6.1.1

  # Local packages
  artbeat_core:
    path: ../artbeat_core
  artbeat_auth:
    path: ../artbeat_auth

  # QR Code generation
  qr_flutter: ^4.1.0

  # Other dependencies
  logger: ^2.0.2
  uuid: ^4.3.3
  share_plus: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true