name: artbeat_artwork
description: Artwork management package for ARTbeat
version: 0.0.2
publish_to: none  # This package is not intended for publishing

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  firebase_storage: ^12.4.7

  # Local Packages
  artbeat_core: 
    path: ../artbeat_core
  artbeat_artist:
    path: ../artbeat_artist

  # Required packages for artwork functionality
  image_picker: ^1.0.7
  share_plus: ^11.0.0
  http: ^1.2.0
  intl: ^0.20.2
  geolocator: ^14.0.1
  provider: ^6.1.2
  
  # Media file support
  video_player: ^2.9.2
  audioplayers: ^6.1.0
  file_picker: ^8.1.6
  video_thumbnail: ^0.5.5
  permission_handler: ^12.0.1

flutter:
  uses-material-design: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
