import 'package:flutter/material.dart';

/// Comprehensive full reaction picker with categorized emoji sections
class FullReactionPicker extends StatefulWidget {
  final void Function(String) onReactionSelected;
  final VoidCallback onClose;

  const FullReactionPicker({
    super.key,
    required this.onReactionSelected,
    required this.onClose,
  });

  @override
  State<FullReactionPicker> createState() => _FullReactionPickerState();
}

class _FullReactionPickerState extends State<FullReactionPicker>
    with TickerProviderStateMixin {
  late TabController _tabController;
  final TextEditingController _searchController = TextEditingController();
  String _searchQuery = '';
  final List<String> _categories = [
    'Recent',
    'Smileys',
    'People',
    'Nature',
    'Food',
    'Activity',
    'Travel',
    'Objects',
    'Symbols',
    'Flags',
  ];

  @override
  void initState() {
    super.initState();
    _tabController = TabController(length: _categories.length, vsync: this);
  }

  @override
  void dispose() {
    _tabController.dispose();
    _searchController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      height: MediaQuery.of(context).size.height * 0.7,
      decoration: const BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.vertical(top: Radius.circular(20)),
      ),
      child: Column(
        children: [
          // Header with search
          _buildHeader(),

          // Tab bar for categories
          _buildTabBar(),

          // Emoji grid
          Expanded(
            child: TabBarView(
              controller: _tabController,
              children: _categories
                  .map((category) => _buildEmojiGrid(category))
                  .toList(),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildHeader() {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        border: Border(bottom: BorderSide(color: Colors.grey.shade200)),
      ),
      child: Column(
        children: [
          // Handle bar
          Center(
            child: Container(
              width: 40,
              height: 4,
              decoration: BoxDecoration(
                color: Colors.grey[300],
                borderRadius: BorderRadius.circular(2),
              ),
            ),
          ),

          const SizedBox(height: 16),

          // Title and close button
          Row(
            children: [
              const Text(
                'Choose a reaction',
                style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
              ),
              const Spacer(),
              IconButton(
                onPressed: widget.onClose,
                icon: const Icon(Icons.close),
                padding: EdgeInsets.zero,
                constraints: const BoxConstraints(),
              ),
            ],
          ),

          const SizedBox(height: 12),

          // Search bar
          TextField(
            controller: _searchController,
            decoration: InputDecoration(
              hintText: 'Search emojis...',
              prefixIcon: const Icon(Icons.search, size: 20),
              border: OutlineInputBorder(
                borderRadius: BorderRadius.circular(25),
                borderSide: BorderSide(color: Colors.grey.shade300),
              ),
              enabledBorder: OutlineInputBorder(
                borderRadius: BorderRadius.circular(25),
                borderSide: BorderSide(color: Colors.grey.shade300),
              ),
              focusedBorder: OutlineInputBorder(
                borderRadius: BorderRadius.circular(25),
                borderSide: BorderSide(color: Theme.of(context).primaryColor),
              ),
              contentPadding: const EdgeInsets.symmetric(
                horizontal: 16,
                vertical: 12,
              ),
            ),
            onChanged: (value) {
              setState(() {
                _searchQuery = value.toLowerCase();
              });
            },
          ),
        ],
      ),
    );
  }

  Widget _buildTabBar() {
    return SizedBox(
      height: 40,
      child: TabBar(
        controller: _tabController,
        isScrollable: true,
        indicatorColor: Theme.of(context).primaryColor,
        labelColor: Theme.of(context).primaryColor,
        unselectedLabelColor: Colors.grey,
        tabs: _categories
            .map((category) => Tab(text: _getCategoryIcon(category)))
            .toList(),
      ),
    );
  }

  String _getCategoryIcon(String category) {
    switch (category) {
      case 'Recent':
        return '🕒';
      case 'Smileys':
        return '😊';
      case 'People':
        return '👥';
      case 'Nature':
        return '🌿';
      case 'Food':
        return '🍎';
      case 'Activity':
        return '⚽';
      case 'Travel':
        return '✈️';
      case 'Objects':
        return '💡';
      case 'Symbols':
        return '❤️';
      case 'Flags':
        return '🏁';
      default:
        return '❓';
    }
  }

  Widget _buildEmojiGrid(String category) {
    final emojis = _getEmojisForCategory(category);
    final filteredEmojis = _searchQuery.isEmpty
        ? emojis
        : emojis
              .where((emoji) => emoji.toLowerCase().contains(_searchQuery))
              .toList();

    return GridView.builder(
      padding: const EdgeInsets.all(16),
      gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
        crossAxisCount: 8,
        crossAxisSpacing: 8,
        mainAxisSpacing: 8,
      ),
      itemCount: filteredEmojis.length,
      itemBuilder: (context, index) {
        final emoji = filteredEmojis[index];
        return GestureDetector(
          onTap: () => widget.onReactionSelected(emoji),
          child: Container(
            decoration: BoxDecoration(
              color: Colors.grey.withValues(alpha: 0.1),
              borderRadius: BorderRadius.circular(8),
            ),
            child: Center(
              child: Text(emoji, style: const TextStyle(fontSize: 24)),
            ),
          ),
        );
      },
    );
  }

  List<String> _getEmojisForCategory(String category) {
    switch (category) {
      case 'Recent':
        return ['👍', '❤️', '😂', '😮', '😢', '😠', '👎', '💯'];
      case 'Smileys':
        return [
          '😀',
          '😃',
          '😄',
          '😁',
          '😆',
          '😅',
          '😂',
          '🤣',
          '😊',
          '😇',
          '🙂',
          '🙃',
          '😉',
          '😌',
          '😍',
          '🥰',
          '😘',
          '😗',
          '😙',
          '😚',
          '😋',
          '😛',
          '😝',
          '😜',
          '🤪',
          '🤨',
          '🧐',
          '🤓',
          '😎',
          '🤩',
          '🥳',
          '😏',
          '😒',
          '😞',
          '😔',
          '😟',
          '😕',
          '🙁',
          '☹️',
          '😣',
          '😖',
          '😫',
          '😩',
          '🥺',
          '😢',
          '😭',
          '😤',
          '😠',
          '😡',
          '🤬',
          '🤯',
          '😳',
          '🥵',
          '🥶',
          '😱',
          '😨',
          '😰',
          '😥',
          '😓',
          '🤗',
          '🤔',
          '🤭',
          '🤫',
          '🤥',
          '😶',
          '😐',
          '😑',
          '😬',
          '🙄',
          '😯',
          '😦',
          '😧',
          '😮',
          '😲',
          '🥱',
          '😴',
          '🤤',
          '😪',
          '😵',
          '🤐',
          '🥴',
          '🤢',
          '🤮',
          '🤧',
          '😷',
          '🤒',
          '🤕',
          '🤑',
          '🤠',
          '😈',
          '👿',
          '👹',
          '👺',
          '🤡',
          '💩',
          '👻',
          '💀',
          '☠️',
          '👽',
          '👾',
          '🤖',
          '🎃',
          '😺',
          '😸',
          '😹',
          '😻',
          '😼',
          '😽',
          '🙀',
          '😿',
          '😾',
        ];
      case 'People':
        return [
          '👋',
          '🤚',
          '🖐️',
          '✋',
          '🖖',
          '👌',
          '🤌',
          '🤏',
          '✌️',
          '🤞',
          '🤟',
          '🤘',
          '🤙',
          '👈',
          '👉',
          '👆',
          '🖕',
          '👇',
          '☝️',
          '👍',
          '👎',
          '👊',
          '✊',
          '🤛',
          '🤜',
          '👏',
          '🙌',
          '👐',
          '🤲',
          '🤝',
          '🙏',
          '✍️',
          '💅',
          '🤳',
          '💪',
          '🦾',
          '🦿',
          '🦵',
          '🦶',
          '👂',
          '🦻',
          '👃',
          '🧠',
          '🫀',
          '🫁',
          '🦷',
          '🦴',
          '👀',
          '👁️',
          '👅',
          '👄',
          '💋',
          '🩸',
        ];
      case 'Nature':
        return [
          '🐶',
          '🐱',
          '🐭',
          '🐹',
          '🐰',
          '🦊',
          '🐻',
          '🐼',
          '🐨',
          '🐯',
          '🦁',
          '🐮',
          '🐷',
          '🐽',
          '🐸',
          '🐵',
          '🙈',
          '🙉',
          '🙊',
          '🐒',
          '🐔',
          '🐧',
          '🐦',
          '🐤',
          '🐣',
          '🐥',
          '🦆',
          '🦅',
          '🦉',
          '🦇',
          '🐺',
          '🐗',
          '🐴',
          '🦄',
          '🐝',
          '🐛',
          '🦋',
          '🐌',
          '🐞',
          '🐜',
          '🦗',
          '🕷️',
          '🦂',
          '🐢',
          '🐍',
          '🦎',
          '🦖',
          '🦕',
          '🐙',
          '🦑',
          '🦐',
          '🦞',
          '🦀',
          '🐡',
          '🐠',
          '🐟',
          '🐬',
          '🐳',
          '🐋',
          '🦈',
          '🐊',
          '🐅',
          '🐆',
          '🦓',
          '🦍',
          '🦧',
          '🐘',
          '🦛',
          '🦏',
          '🐪',
          '🐫',
          '🦒',
          '🦘',
          '🐃',
          '🐂',
          '🐄',
          '🐎',
          '🐖',
          '🐏',
          '🐑',
          '🦙',
          '🐐',
          '🦌',
          '🐕',
          '🐩',
          '🦮',
          '🐕‍🦺',
          '🐈',
          '🐈‍⬛',
          '🐓',
          '🦃',
          '🦚',
          '🦜',
          '🦢',
          '🦩',
          '🕊️',
          '🐇',
          '🦝',
          '🦨',
          '🦡',
          '🦦',
          '🦥',
          '🐁',
          '🐀',
          '🐿️',
          '🦔',
          '🐾',
          '🐉',
          '🐊',
          '🌿',
          '☘️',
          '🍀',
          '🎋',
          '🎍',
          '🌾',
          '🌵',
          '🌲',
          '🌳',
          '🌴',
          '🌱',
          '🌿',
          '☘️',
          '🍀',
          '🎋',
          '🎍',
          '🌾',
          '🌵',
          '🌲',
          '🌳',
          '🌴',
          '🌸',
          '🌺',
          '🌻',
          '🌷',
          '🌹',
          '🥀',
          '🌷',
          '🌼',
          '🌻',
          '🌺',
          '🌸',
          '🌺',
          '🌻',
          '🌷',
          '🌹',
          '🥀',
          '🌷',
          '🌼',
        ];
      case 'Food':
        return [
          '🍎',
          '🍊',
          '🍋',
          '🍌',
          '🍉',
          '🍇',
          '🍓',
          '🫐',
          '🍈',
          '🍒',
          '🍑',
          '🥭',
          '🍍',
          '🥥',
          '🥝',
          '🍅',
          '🍆',
          '🥑',
          '🥦',
          '🥬',
          '🥒',
          '🌶️',
          '🫑',
          '🌽',
          '🥕',
          '🫒',
          '🧄',
          '🧅',
          '🥔',
          '🍠',
          '🥐',
          '🥖',
          '🍞',
          '🥨',
          '🥯',
          '🧀',
          '🥚',
          '🍳',
          '🧈',
          '🥞',
          '🧇',
          '🥓',
          '🥩',
          '🍗',
          '🍖',
          '🦴',
          '🌭',
          '🍔',
          '🍟',
          '🍕',
          '🫓',
          '🥙',
          '🌮',
          '🌯',
          '🫔',
          '🥗',
          '🥘',
          '🫕',
          '🍝',
          '🍜',
          '🍲',
          '🍛',
          '🍣',
          '🍱',
          '🥟',
          '🦪',
          '🍤',
          '🍙',
          '🍚',
          '🍘',
          '🍥',
          '🥠',
          '🥮',
          '🍢',
          '🍡',
          '🍧',
          '🍨',
          '🍦',
          '🥧',
          '🧁',
          '🍰',
          '🎂',
          '🍮',
          '🍭',
          '🍬',
          '🍫',
          '🍿',
          '🍩',
          '🍪',
          '🌰',
          '🥜',
          '🍯',
          '🥛',
          '🍼',
          '☕',
          '🫖',
          '🍵',
          '🧃',
          '🥤',
          '🧋',
          '🍶',
          '🍺',
          '🍻',
          '🥂',
          '🍷',
          '🥃',
          '🍸',
          '🍹',
          '🧉',
          '🍾',
        ];
      case 'Activity':
        return [
          '⚽',
          '🏀',
          '🏈',
          '⚾',
          '🥎',
          '🎾',
          '🏐',
          '🏉',
          '🥏',
          '🎱',
          '🪀',
          '🏓',
          '🏸',
          '🏒',
          '🏑',
          '🥍',
          '🏏',
          '🪃',
          '🥅',
          '⛳',
          '🪁',
          '🏹',
          '🎣',
          '🤿',
          '🥊',
          '🥋',
          '🎽',
          '🛹',
          '🛷',
          '⛸️',
          '🥌',
          '🎿',
          '⛷️',
          '🏂',
          '🪂',
          '🏋️',
          '🤸',
          '🤼',
          '🤽',
          '🤾',
          '🧘',
          '🏃',
          '🚶',
          '🧎',
          '🧍',
          '🤺',
          '🏇',
          '⛹️',
          '🏌️',
          '🏄',
          '🚣',
          '🏊',
          '⛹️‍♀️',
          '🏋️‍♀️',
          '🚴',
          '🚵',
          '🏆',
          '🥇',
          '🥈',
          '🥉',
          '🏅',
          '🎖️',
          '🏵️',
          '🎗️',
          '🎫',
          '🎟️',
          '🎪',
          '🤹',
          '🎭',
          '🩰',
          '🎨',
          '🎬',
          '🎤',
          '🎧',
          '🎼',
          '🎹',
          '🥁',
          '🪘',
          '🎷',
          '🎺',
          '🪗',
          '🎸',
          '🪕',
          '🎻',
          '🎲',
          '♠️',
          '♥️',
          '♦️',
          '♣️',
          '🃏',
          '🀄',
          '🎴',
        ];
      case 'Travel':
        return [
          '🚗',
          '🚕',
          '🚙',
          '🚌',
          '🚎',
          '🏎️',
          '🚓',
          '🚑',
          '🚒',
          '🚐',
          '🚚',
          '🚛',
          '🚜',
          '🏍️',
          '🛵',
          '🚲',
          '🛴',
          '🛹',
          '🚁',
          '🚟',
          '🚠',
          '🚡',
          '🛤️',
          '🛣️',
          '🗺️',
          '⛽',
          '🚨',
          '🚥',
          '🚦',
          '🛑',
          '🚧',
          '⚓',
          '⛵',
          '🛶',
          '🚤',
          '🛳️',
          '⛴️',
          '🛥️',
          '🚢',
          '✈️',
          '🛩️',
          '🛫',
          '🛬',
          '🪂',
          '💺',
          '🚀',
          '🛸',
          '🚁',
          '🚟',
          '🚠',
          '🚡',
          '🛤️',
          '🛣️',
          '🗺️',
          '⛽',
          '🚨',
          '🚥',
          '🚦',
          '🛑',
          '🚧',
          '⚓',
          '⛵',
          '🛶',
          '🚤',
          '🛳️',
          '⛴️',
          '🛥️',
          '🚢',
          '🛩️',
          '🛫',
          '🛬',
          '🪂',
          '💺',
          '🚀',
          '🛸',
          '🏖️',
          '⛰️',
          '🏔️',
          '🗻',
          '🌋',
          '🗾',
          '🏙️',
          '🌆',
          '🌃',
          '🌉',
          '🌌',
        ];
      case 'Objects':
        return [
          '⌚',
          '📱',
          '📲',
          '💻',
          '⌨️',
          '🖥️',
          '🖨️',
          '🖱️',
          '🖲️',
          '🕹️',
          '🗜️',
          '💽',
          '💾',
          '💿',
          '📀',
          '📼',
          '📷',
          '📸',
          '📹',
          '🎥',
          '📽️',
          '🎞️',
          '📞',
          '☎️',
          '📟',
          '📠',
          '📺',
          '📻',
          '🎙️',
          '🎚️',
          '🎛️',
          '🧭',
          '⏱️',
          '⏲️',
          '⏰',
          '🕰️',
          '⌛',
          '⏳',
          '📡',
          '🔋',
          '🔌',
          '💡',
          '🔦',
          '🕯️',
          '🪔',
          '🧯',
          '🛢️',
          '💸',
          '💵',
          '💴',
          '💶',
          '💷',
          '💰',
          '💳',
          '💎',
          '⚖️',
          '🪜',
          '🧰',
          '🪛',
          '🔧',
          '🔨',
          '⚒️',
          '🛠️',
          '⛏️',
          '🔩',
          '⚙️',
          '🗜️',
          '⚖️',
          '🦯',
          '🔗',
          '⛓️',
          '🪝',
          '🧼',
          '🪒',
          '🧽',
          '🧴',
          '🛁',
          '🪤',
          '🪠',
          '🧹',
          '🧺',
          '🪣',
          '🧻',
          '🧷',
          '🧹',
          '🧺',
          '🪣',
          '🧻',
          '🧷',
          '👓',
          '🕶️',
          '🥽',
          '🥼',
          '🦺',
          '👔',
          '👕',
          '👖',
          '🧣',
          '🧤',
          '🧥',
          '🧦',
          '👗',
          '👘',
          '🥻',
          '🩱',
          '🩲',
          '🩳',
          '👙',
          '👚',
          '👛',
          '👜',
          '👝',
          '🛍️',
          '🎒',
          '🩼',
          '🦽',
          '🦼',
          '🛴',
          '🛹',
          '🎪',
          '🎭',
          '🩰',
          '🎨',
          '🎬',
          '🎤',
          '🎧',
          '🎼',
          '🎹',
          '🥁',
          '🪘',
          '🎷',
          '🎺',
          '🪗',
          '🎸',
          '🪕',
          '🎻',
          '🎲',
          '♠️',
          '♥️',
          '♦️',
          '♣️',
          '🃏',
          '🀄',
          '🎴',
        ];
      case 'Symbols':
        return [
          '❤️',
          '🧡',
          '💛',
          '💚',
          '💙',
          '💜',
          '🖤',
          '🤍',
          '🤎',
          '💔',
          '❤️‍🔥',
          '❤️‍🩹',
          '💕',
          '💞',
          '💓',
          '💗',
          '💖',
          '💘',
          '💝',
          '💟',
          '☮️',
          '✝️',
          '☪️',
          '🕉️',
          '☸️',
          '✡️',
          '🔯',
          '🕎',
          '☯️',
          '☦️',
          '🛐',
          '⛎',
          '♈',
          '♉',
          '♊',
          '♋',
          '♌',
          '♍',
          '♎',
          '♏',
          '♐',
          '♑',
          '♒',
          '♓',
          '🆔',
          '⚛️',
          '🉑',
          '☢️',
          '☣️',
          '📴',
          '📳',
          '🈶',
          '🈚',
          '🈸',
          '🈺',
          '🈷️',
          '✴️',
          '🆚',
          '💮',
          '🉐',
          '㊙️',
          '㊗️',
          '🈴',
          '🈵',
          '🈹',
          '🈲',
          '🅰️',
          '🅱️',
          '🆎',
          '🆑',
          '🅾️',
          '🆘',
          '❌',
          '⭕',
          '🛑',
          '⛔',
          '📛',
          '🚫',
          '💯',
          '💢',
          '♨️',
          '🚷',
          '🚯',
          '🚳',
          '🚱',
          '🔞',
          '📵',
          '🚭',
          '♿',
          '🅿️',
          '🛗',
          '🈳',
          '🈂️',
          '🛂',
          '🛃',
          '🛄',
          '🛅',
          '⚠️',
          '🚸',
          '⛽',
          '🚰',
          '♻️',
          '🚮',
          '🚾',
          '🛜',
          '📶',
          '📳',
          '📴',
          '♀️',
          '♂️',
          '⚧',
          '✖️',
          '➕',
          '➖',
          '➗',
          '🟰',
          '♾️',
          '‼️',
          '⁉️',
          '❓',
          '❔',
          '❕',
          '❗',
          '〰️',
          '💱',
          '💲',
          '⚕️',
          '♻️',
          '⚜️',
          '🔱',
          '📛',
          '🔰',
          '⭕',
          '✅',
          '☑️',
          '✔️',
          '❌',
          '❎',
          '➰',
          '➿',
          '〽️',
          '✳️',
          '✴️',
          '❇️',
          '©️',
          '®️',
          '™️',
          '🔟',
          '🔠',
          '🔡',
          '🔢',
          '🔣',
          '🔤',
          '🅰️',
          '🆎',
          '🅱️',
          '🆑',
          '🆒',
          '🆓',
          'ℹ️',
          '🆔',
          'Ⓜ️',
          '🆕',
          '🆖',
          '🅾️',
          '🆗',
          '🅿️',
          '🆘',
          '🆙',
          '🆚',
          '🈁',
          '🈂️',
          '🈷️',
          '🈶',
          '🈯',
          '🉐',
          '🈹',
          '🈚',
          '🈲',
          '🉑',
          '🈸',
          '🈴',
          '🈳',
          '㊗️',
          '㊙️',
          '🈺',
          '🈵',
          '🔴',
          '🟠',
          '🟡',
          '🟢',
          '🔵',
          '🟣',
          '🟤',
          '⚫',
          '⚪',
          '🟥',
          '🟧',
          '🟨',
          '🟩',
          '🟦',
          '🟪',
          '🟫',
          '⬛',
          '⬜',
          '🟪',
          '🟦',
          '🟩',
          '🟨',
          '🟧',
          '🟥',
          '🟫',
          '🟤',
          '🟣',
          '🟢',
          '🟡',
          '🟠',
          '🔴',
          '🔵',
          '⚫',
          '⚪',
          '⬛',
          '⬜',
        ];
      case 'Flags':
        return [
          '🏁',
          '🚩',
          '🎌',
          '🏴',
          '🏳️',
          '🏳️‍🌈',
          '🏳️‍⚧️',
          '🏴‍☠️',
          '🇺🇸',
          '🇬🇧',
          '🇨🇦',
          '🇦🇺',
          '🇩🇪',
          '🇫🇷',
          '🇯🇵',
          '🇰🇷',
          '🇨🇳',
          '🇮🇳',
          '🇧🇷',
          '🇲🇽',
          '🇷🇺',
          '🇮🇹',
          '🇪🇸',
          '🇳🇱',
          '🇸🇪',
          '🇳🇴',
          '🇩🇰',
          '🇫🇮',
          '🇵🇱',
          '🇹🇷',
          '🇬🇷',
          '🇵🇹',
          '🇨🇿',
          '🇭🇺',
          '🇮🇱',
          '🇸🇦',
          '🇦🇪',
          '🇪🇬',
          '🇿🇦',
          '🇳🇬',
          '🇰🇪',
          '🇲🇦',
          '🇹🇳',
          '🇬🇭',
          '🇨🇮',
          '🇸🇳',
          '🇨🇲',
          '🇲🇬',
          '🇲🇺',
          '🇸🇨',
          '🇲🇾',
          '🇸🇬',
          '🇹🇭',
          '🇮🇩',
          '🇵🇭',
          '🇻🇳',
          '🇭🇰',
          '🇹🇼',
          '🇲🇴',
          '🇰🇭',
          '🇱🇦',
          '🇲🇲',
          '🇧🇩',
          '🇱🇰',
          '🇳🇵',
          '🇵🇰',
          '🇦🇫',
          '🇮🇷',
          '🇮🇶',
          '🇰🇼',
          '🇶🇦',
          '🇧🇭',
          '🇴🇲',
          '🇾🇪',
          '🇯🇴',
          '🇱🇧',
          '🇸🇾',
          '🇵🇸',
          '🇯🇴',
          '🇰🇼',
          '🇶🇦',
          '🇧🇭',
          '🇴🇲',
          '🇾🇪',
          '🇱🇧',
          '🇸🇾',
          '🇵🇸',
          '🇮🇱',
          '🇸🇦',
          '🇦🇪',
          '🇪🇬',
          '🇿🇦',
          '🇳🇬',
          '🇰🇪',
          '🇲🇦',
          '🇹🇳',
          '🇬🇭',
          '🇨🇮',
          '🇸🇳',
          '🇨🇲',
          '🇲🇬',
          '🇲🇺',
          '🇸🇨',
          '🇲🇾',
          '🇸🇬',
          '🇹🇭',
          '🇮🇩',
          '🇵🇭',
          '🇻🇳',
          '🇭🇰',
          '🇹🇼',
          '🇲🇴',
          '🇰🇭',
          '🇱🇦',
          '🇲🇲',
          '🇧🇩',
          '🇱🇰',
          '🇳🇵',
          '🇵🇰',
          '🇦🇫',
          '🇮🇷',
          '🇮🇶',
        ];
      default:
        return [];
    }
  }
}
