name: artbeat_core
description: Core components for the ARTbeat application
version: 0.0.1
publish_to: 'none'
homepage: https://artbeat.app

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Feature modules
  artbeat_art_walk:
    path: ../artbeat_art_walk
  artbeat_community:
    path: ../artbeat_community
  artbeat_artwork:
    path: ../artbeat_artwork
  artbeat_artist:
    path: ../artbeat_artist
  artbeat_settings:
    path: ../artbeat_settings
  artbeat_profile:
    path: ../artbeat_profile
  artbeat_auth:
    path: ../artbeat_auth

  # Utils
  logging: ^1.2.0
  shared_preferences: ^2.2.2
  firebase_core: ^2.24.2
  firebase_analytics: ^10.8.0
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6  # Compatible with firebase_core 2.24.2
  firebase_app_check: ^0.2.1+8  # Compatible with firebase_core 2.24.2
  
  # Math and utils
  vector_math: ^2.1.4  # Required for Matrix4 operations
  
  # Utilities
  provider: ^6.1.1
  intl: ^0.19.0
  http: ^1.2.0
  flutter_cache_manager: ^3.3.1
  
  # File system and storage
  path_provider: ^2.1.2
  
  # Location services
  geolocator: ^11.0.0
  geocoding: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/default_profile.png
    - assets/images/artbeat_logo.png
