name: artbeat_core
description: Core components for the ARTbeat application
version: 0.0.1
publish_to: 'none'
homepage: https://artbeat.app

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter

  # Environment configuration
  flutter_dotenv: ^5.1.0

  # Local modules
  artbeat_admin:
    path: ../artbeat_admin
  artbeat_art_walk:
    path: ../artbeat_art_walk
  artbeat_artist:
    path: ../artbeat_artist
  artbeat_artwork:
    path: ../artbeat_artwork
  artbeat_auth:
    path: ../artbeat_auth
  artbeat_capture:
    path: ../artbeat_capture
  artbeat_community:
    path: ../artbeat_community
  artbeat_messaging:
    path: ../artbeat_messaging
  artbeat_profile:
    path: ../artbeat_profile
  artbeat_settings:
    path: ../artbeat_settings

  # Firebase - versions aligned with iOS SDK 10.25.0
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  firebase_storage: ^12.4.7
  firebase_analytics: ^11.5.0
  firebase_app_check: ^0.3.2+7

  # Location services
  geolocator: ^14.0.1
  geocoding: ^4.0.0

  # State management
  provider: ^6.1.1

  # Storage
  shared_preferences: ^2.2.2
  flutter_cache_manager: ^3.3.1


  # Payments
  flutter_stripe: ^11.1.0
  http: ^1.0.0

  # Date formatting
  intl: ^0.20.2

  # Share functionality
  share_plus: ^11.0.0

  # Logging
  logging: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
