name: artbeat_core
description: Core components for the ARTbeat application
version: 0.0.1
publish_to: 'none'
homepage: https://artbeat.app

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Feature modules
  artbeat_art_walk:
    path: ../artbeat_art_walk
  artbeat_community:
    path: ../artbeat_community
  artbeat_artwork:
    path: ../artbeat_artwork
  artbeat_capture:
    path: ../artbeat_capture
  artbeat_artist:
    path: ../artbeat_artist

  # Firebase dependencies (updated to compatible versions)
  firebase_core: ^2.32.0  # Downgrade to be compatible with firebase_storage
  firebase_auth: ^4.17.4  # Matching version for firebase_core 2.32.0
  cloud_firestore: ^4.15.4  # Matching version for firebase_core 2.32.0
  firebase_storage: ^11.7.7  # Latest version compatible with firebase_core 2.32.0
  
  # Utilities
  provider: ^6.0.5
  intl: ^0.19.0
  http: ^1.2.0 # Added for API requests
  
  # Location services
  geolocator: ^11.0.0 # Added for location services
  geocoding: ^2.2.0 # Added for converting coordinates to addresses

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/default_profile.png
