#!/usr/bin/env python3
"""Merge translations for the artbeat_admin package into assets translations.

This is modeled after scripts/merge_ad_translations.py and merges a curated
translation mapping (for admin-related keys) into the project's translation
JSON files for es/fr/de/pt/zh. It will also ensure en.json contains keys
referenced and create them if missing.
"""
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
EN_FILE = ROOT / "assets" / "translations" / "en.json"
TRANSLATIONS_DIR = ROOT / "assets" / "translations"
ADMIN_DATA = ROOT / "artbeat_admin_texts_data.json"
TARGET_LANGS = ["es", "fr", "de", "pt", "zh"]

PLACEHOLDER_REGEX = re.compile(r"\{[^}]+\}|\$\{[^}]+\}|\$[a-zA-Z_]\w*")


def extract_placeholders(s: str):
    return set(PLACEHOLDER_REGEX.findall(s))


# Curated translations generated by the AI for the matched keys (from previous step)
# Only keys which were known/matched are included to avoid overwriting unrelated keys.
TRANSLATIONS = {
    "es": {
        "admin_admin_payment_text_avg_transaction_4": "Transacción promedio",
        "admin_admin_payment_text_export_selected_36": "Exportar seleccionados",
        "admin_admin_payment_text_process_refund_2": "Procesar reembolso",
        "admin_admin_payment_text_total_refunds_5": "Total de reembolsos",
        "admin_admin_payment_text_total_transactions_3": "Total de transacciones",
        "admin_admin_security_center_text_office_network_16": "Red de oficina",
        "admin_admin_settings_text_content_settings_4": "Configuración de contenido",
        "admin_admin_settings_text_danger_zone_9": "Zona de peligro",
        "admin_admin_settings_text_general_settings_2": "Configuración general",
        "admin_admin_settings_text_maintenance_settings_8": "Configuración de mantenimiento",
        "admin_admin_settings_text_user_settings_3": "Configuración de usuario",
        "admin_admin_system_monitoring_text_avg_session_9": "Duración promedio de sesión",
        "admin_admin_system_monitoring_text_cpu_usage_1": "Uso de CPU",
        "admin_admin_system_monitoring_text_critical_alerts_5": "Alertas críticas",
        "admin_admin_system_monitoring_text_memory_usage_2": "Uso de memoria",
        "admin_admin_system_monitoring_text_peak_today_8": "Pico de hoy",
        "admin_admin_system_monitoring_text_response_time_4": "Tiempo de respuesta",
        "admin_admin_system_monitoring_text_warning_alerts_6": "Alertas de advertencia",
        "admin_admin_user_detail_text_user_details_1": "Detalles del usuario",
        "admin_dashboard_active_users": "Usuarios activos",
        "admin_dashboard_manage_users": "Administrar usuarios",
        "admin_dashboard_pending_reviews": "Revisiones pendientes",
        "admin_dashboard_recent_alerts": "Alertas recientes",
        "admin_dashboard_reports": "Informes",
        "admin_dashboard_revenue_growth": "Crecimiento de ingresos",
        "admin_dashboard_system_health": "Estado del sistema",
        "admin_dashboard_total_users": "Total de usuarios",
        "admin_drawer_menu_admin_settings": "Configuración de administrador",
        "admin_drawer_menu_payments": "Administración de pagos",
        "admin_header_menu_user_management": "Gestión de usuarios",
        "admin_migration_dialog_run_migration_title": "Ejecutar migración",
        "admin_modern_unified_admin_dashboard_hint_admin_command_center_1": "Centro de comando de administrador",
        "admin_unified_admin_dashboard_text_admin_dashboard_1": "Panel de administración",
        "admin_unified_admin_dashboard_text_view_details_16": "Ver detalles",
        "ads_ad_report_text_cancel": "Cancelar",
        "ads_my_ads_text_this_action_cannot_4": "Esta acción no se puede deshacer.",
        "artist_dashboard_recent_activity": "Actividad reciente",
        "artwork_analytics_total_revenue": "Ingresos totales",
        "artwork_search_hint": "Buscar obra...",
        "auth_register_password": "Contraseña",
        "capture_admin_content_moderation_text_content_moderation": "Moderación de contenido",
        "capture_admin_content_moderation_text_reported_47": "Reportado",
        "common_search": "Buscar",
        "core_settings_actions": "Acciones",
        "core_settings_title": "Configuración del sistema",
        "curated_gallery_error_unknown": "Error desconocido",
        "dashboard_title": "Panel",
        "enhanced_upload_tags_label": "Etiquetas",
        "event_analytics_revenue": "Ingresos",
        "event_analytics_total_events": "Total de eventos",
        "event_mod_analytics": "Analítica",
        "event_mod_pending_review": "Pendiente de revisión",
        "event_mod_status_label": "Estado",
        "events_location": "Ubicación",
        "messaging_chat_notification_settings_text_notification_settings_2": "Configuración de notificaciones",
        "messaging_enhanced_messaging_dashboard_text_no_recent_activity": "Sin actividad reciente",
        "messaging_media_title": "Medios",
        "messaging_online_users": "Usuarios en línea",
        "messaging_save_media": "Guardar",
        "search_filter_all": "Todos",
        "settings_bio": "Biografía",
        "settings_enable_email_notifications": "Habilitar notificaciones por correo",
        "settings_enable_push_notifications": "Habilitar notificaciones push",
        "settings_security_title": "Configuración de seguridad",
        "settings_username": "Nombre de usuario",
        "system_settings_account_created": "Cuenta creada",
        "system_settings_email": "Correo electrónico",
        "user_dashboard_achievements": "Logros",
        "user_dashboard_quick_actions": "Acciones rápidas",
        "written_content_upload_description_label": "Descripción",
        "written_content_upload_step_content": "Contenido",
        "written_content_upload_step_details": "Detalles",
        "written_content_upload_title_label": "Título"
    },
    "fr": {
        "admin_admin_payment_text_avg_transaction_4": "Transaction moyenne",
        "admin_admin_payment_text_export_selected_36": "Exporter sélectionnés",
        "admin_admin_payment_text_process_refund_2": "Traiter le remboursement",
        "admin_admin_payment_text_total_refunds_5": "Total des remboursements",
        "admin_admin_payment_text_total_transactions_3": "Total des transactions",
        "admin_admin_security_center_text_office_network_16": "Réseau de bureau",
        "admin_admin_settings_text_content_settings_4": "Paramètres de contenu",
        "admin_admin_settings_text_danger_zone_9": "Zone dangereuse",
        "admin_admin_settings_text_general_settings_2": "Paramètres généraux",
        "admin_admin_settings_text_maintenance_settings_8": "Paramètres de maintenance",
        "admin_admin_settings_text_user_settings_3": "Paramètres utilisateur",
        "admin_admin_system_monitoring_text_avg_session_9": "Durée de session moyenne",
        "admin_admin_system_monitoring_text_cpu_usage_1": "Utilisation du processeur",
        "admin_admin_system_monitoring_text_critical_alerts_5": "Alertes critiques",
        "admin_admin_system_monitoring_text_memory_usage_2": "Utilisation de la mémoire",
        "admin_admin_system_monitoring_text_peak_today_8": "Pic aujourd'hui",
        "admin_admin_system_monitoring_text_response_time_4": "Temps de réponse",
        "admin_admin_system_monitoring_text_warning_alerts_6": "Alertes d'avertissement",
        "admin_admin_user_detail_text_user_details_1": "Détails de l'utilisateur",
        "admin_dashboard_active_users": "Utilisateurs actifs",
        "admin_dashboard_manage_users": "Gérer les utilisateurs",
        "admin_dashboard_pending_reviews": "Avis en attente",
        "admin_dashboard_recent_alerts": "Alertes récentes",
        "admin_dashboard_reports": "Rapports",
        "admin_dashboard_revenue_growth": "Croissance des revenus",
        "admin_dashboard_system_health": "Santé du système",
        "admin_dashboard_total_users": "Total des utilisateurs",
        "admin_drawer_menu_admin_settings": "Paramètres administrateur",
        "admin_drawer_menu_payments": "Gestion des paiements",
        "admin_header_menu_user_management": "Gestion des utilisateurs",
        "admin_migration_dialog_run_migration_title": "Exécuter la migration",
        "admin_modern_unified_admin_dashboard_hint_admin_command_center_1": "Centre de commandes administrateur",
        "admin_unified_admin_dashboard_text_admin_dashboard_1": "Tableau de bord administrateur",
        "admin_unified_admin_dashboard_text_view_details_16": "Voir les détails",
        "ads_ad_report_text_cancel": "Annuler",
        "ads_my_ads_text_this_action_cannot_4": "Cette action ne peut pas être annulée.",
        "artist_dashboard_recent_activity": "Activité récente",
        "artwork_analytics_total_revenue": "Revenu total",
        "artwork_search_hint": "Rechercher une œuvre...",
        "auth_register_password": "Mot de passe",
        "capture_admin_content_moderation_text_content_moderation": "Modération de contenu",
        "capture_admin_content_moderation_text_reported_47": "Signalé",
        "common_search": "Rechercher",
        "core_settings_actions": "Actions",
        "core_settings_title": "Paramètres du système",
        "curated_gallery_error_unknown": "Erreur inconnue",
        "dashboard_title": "Tableau de bord",
        "enhanced_upload_tags_label": "Étiquettes",
        "event_analytics_revenue": "Revenu",
        "event_analytics_total_events": "Nombre total d'événements",
        "event_mod_analytics": "Analytique",
        "event_mod_pending_review": "En attente d'examen",
        "event_mod_status_label": "Statut",
        "events_location": "Lieu",
        "messaging_chat_notification_settings_text_notification_settings_2": "Paramètres de notification",
        "messaging_enhanced_messaging_dashboard_text_no_recent_activity": "Aucune activité récente",
        "messaging_media_title": "Médias",
        "messaging_online_users": "Utilisateurs en ligne",
        "messaging_save_media": "Enregistrer",
        "search_filter_all": "Tous",
        "settings_bio": "Biographie",
        "settings_enable_email_notifications": "Activer les notifications par e-mail",
        "settings_enable_push_notifications": "Activer les notifications push",
        "settings_security_title": "Paramètres de sécurité",
        "settings_username": "Nom d'utilisateur",
        "system_settings_account_created": "Compte créé",
        "system_settings_email": "E-mail",
        "user_dashboard_achievements": "Succès",
        "user_dashboard_quick_actions": "Actions rapides",
        "written_content_upload_description_label": "Description",
        "written_content_upload_step_content": "Contenu",
        "written_content_upload_step_details": "Détails",
        "written_content_upload_title_label": "Titre"
    },
    "de": {
        "admin_admin_payment_text_avg_transaction_4": "Durchschnittliche Transaktion",
        "admin_admin_payment_text_export_selected_36": "Ausgewählte exportieren",
        "admin_admin_payment_text_process_refund_2": "Rückerstattung verarbeiten",
        "admin_admin_payment_text_total_refunds_5": "Gesamte Rückerstattungen",
        "admin_admin_payment_text_total_transactions_3": "Gesamttransaktionen",
        "admin_admin_security_center_text_office_network_16": "Büro-Netzwerk",
        "admin_admin_settings_text_content_settings_4": "Inhalts-Einstellungen",
        "admin_admin_settings_text_danger_zone_9": "Gefahrenzone",
        "admin_admin_settings_text_general_settings_2": "Allgemeine Einstellungen",
        "admin_admin_settings_text_maintenance_settings_8": "Wartungseinstellungen",
        "admin_admin_settings_text_user_settings_3": "Benutzereinstellungen",
        "admin_admin_system_monitoring_text_avg_session_9": "Durchschnittliche Sitzungsdauer",
        "admin_admin_system_monitoring_text_cpu_usage_1": "CPU-Auslastung",
        "admin_admin_system_monitoring_text_critical_alerts_5": "Kritische Warnungen",
        "admin_admin_system_monitoring_text_memory_usage_2": "Speicherauslastung",
        "admin_admin_system_monitoring_text_peak_today_8": "Heutiger Spitzenwert",
        "admin_admin_system_monitoring_text_response_time_4": "Antwortzeit",
        "admin_admin_system_monitoring_text_warning_alerts_6": "Warnmeldungen",
        "admin_admin_user_detail_text_user_details_1": "Benutzerdetails",
        "admin_dashboard_active_users": "Aktive Nutzer",
        "admin_dashboard_manage_users": "Benutzer verwalten",
        "admin_dashboard_pending_reviews": "Ausstehende Prüfungen",
        "admin_dashboard_recent_alerts": "Letzte Warnungen",
        "admin_dashboard_reports": "Berichte",
        "admin_dashboard_revenue_growth": "Umsatzwachstum",
        "admin_dashboard_system_health": "Systemzustand",
        "admin_dashboard_total_users": "Gesamtanzahl der Nutzer",
        "admin_drawer_menu_admin_settings": "Administrator-Einstellungen",
        "admin_drawer_menu_payments": "Zahlungsverwaltung",
        "admin_header_menu_user_management": "Benutzerverwaltung",
        "admin_migration_dialog_run_migration_title": "Migration ausführen",
        "admin_modern_unified_admin_dashboard_hint_admin_command_center_1": "Admin-Kommandozentrale",
        "admin_unified_admin_dashboard_text_admin_dashboard_1": "Admin-Dashboard",
        "admin_unified_admin_dashboard_text_view_details_16": "Details ansehen",
        "ads_ad_report_text_cancel": "Abbrechen",
        "ads_my_ads_text_this_action_cannot_4": "Diese Aktion kann nicht rückgängig gemacht werden.",
        "artist_dashboard_recent_activity": "Aktuelle Aktivitäten",
        "artwork_analytics_total_revenue": "Gesamteinnahmen",
        "artwork_search_hint": "Kunstwerk suchen...",
        "auth_register_password": "Passwort",
        "capture_admin_content_moderation_text_content_moderation": "Inhaltsmoderation",
        "capture_admin_content_moderation_text_reported_47": "Gemeldet",
        "common_search": "Suchen",
        "core_settings_actions": "Aktionen",
        "core_settings_title": "Systemeinstellungen",
        "curated_gallery_error_unknown": "Unbekannter Fehler",
        "dashboard_title": "Dashboard",
        "enhanced_upload_tags_label": "Tags",
        "event_analytics_revenue": "Umsatz",
        "event_analytics_total_events": "Gesamtanzahl Veranstaltungen",
        "event_mod_analytics": "Analyse",
        "event_mod_pending_review": "Ausstehende Prüfung",
        "event_mod_status_label": "Status",
        "events_location": "Standort",
        "messaging_chat_notification_settings_text_notification_settings_2": "Benachrichtigungseinstellungen",
        "messaging_enhanced_messaging_dashboard_text_no_recent_activity": "Keine Aktivitäten in letzter Zeit",
        "messaging_media_title": "Medien",
        "messaging_online_users": "Online-Nutzer",
        "messaging_save_media": "Speichern",
        "search_filter_all": "Alle",
        "settings_bio": "Bio",
        "settings_enable_email_notifications": "E-Mail-Benachrichtigungen aktivieren",
        "settings_enable_push_notifications": "Push-Benachrichtigungen aktivieren",
        "settings_security_title": "Sicherheitseinstellungen",
        "settings_username": "Benutzername",
        "system_settings_account_created": "Konto erstellt",
        "system_settings_email": "E-Mail",
        "user_dashboard_achievements": "Erfolge",
        "user_dashboard_quick_actions": "Schnellaktionen",
        "written_content_upload_description_label": "Beschreibung",
        "written_content_upload_step_content": "Inhalt",
        "written_content_upload_step_details": "Details",
        "written_content_upload_title_label": "Titel"
    },
    "pt": {
        "admin_admin_payment_text_avg_transaction_4": "Transação média",
        "admin_admin_payment_text_export_selected_36": "Exportar selecionados",
        "admin_admin_payment_text_process_refund_2": "Processar reembolso",
        "admin_admin_payment_text_total_refunds_5": "Total de reembolsos",
        "admin_admin_payment_text_total_transactions_3": "Total de transações",
        "admin_admin_security_center_text_office_network_16": "Rede do escritório",
        "admin_admin_settings_text_content_settings_4": "Configurações de conteúdo",
        "admin_admin_settings_text_danger_zone_9": "Zona de perigo",
        "admin_admin_settings_text_general_settings_2": "Configurações gerais",
        "admin_admin_settings_text_maintenance_settings_8": "Configurações de manutenção",
        "admin_admin_settings_text_user_settings_3": "Configurações do usuário",
        "admin_admin_system_monitoring_text_avg_session_9": "Sessão média",
        "admin_admin_system_monitoring_text_cpu_usage_1": "Uso da CPU",
        "admin_admin_system_monitoring_text_critical_alerts_5": "Alertas críticos",
        "admin_admin_system_monitoring_text_memory_usage_2": "Uso de memória",
        "admin_admin_system_monitoring_text_peak_today_8": "Pico hoje",
        "admin_admin_system_monitoring_text_response_time_4": "Tempo de resposta",
        "admin_admin_system_monitoring_text_warning_alerts_6": "Alertas de aviso",
        "admin_admin_user_detail_text_user_details_1": "Detalhes do usuário",
        "admin_dashboard_active_users": "Usuários ativos",
        "admin_dashboard_manage_users": "Gerenciar usuários",
        "admin_dashboard_pending_reviews": "Revisões pendentes",
        "admin_dashboard_recent_alerts": "Alertas recentes",
        "admin_dashboard_reports": "Relatórios",
        "admin_dashboard_revenue_growth": "Crescimento de receita",
        "admin_dashboard_system_health": "Saúde do sistema",
        "admin_dashboard_total_users": "Total de usuários",
        "admin_drawer_menu_admin_settings": "Configurações do administrador",
        "admin_drawer_menu_payments": "Gerenciamento de pagamentos",
        "admin_header_menu_user_management": "Gerenciamento de usuários",
        "admin_migration_dialog_run_migration_title": "Executar migração",
        "admin_modern_unified_admin_dashboard_hint_admin_command_center_1": "Centro de comando do administrador",
        "admin_unified_admin_dashboard_text_admin_dashboard_1": "Painel do administrador",
        "admin_unified_admin_dashboard_text_view_details_16": "Ver detalhes",
        "ads_ad_report_text_cancel": "Cancelar",
        "ads_my_ads_text_this_action_cannot_4": "Esta ação não pode ser desfeita.",
        "artist_dashboard_recent_activity": "Atividade recente",
        "artwork_analytics_total_revenue": "Receita total",
        "artwork_search_hint": "Pesquisar obra...",
        "auth_register_password": "Senha",
        "capture_admin_content_moderation_text_content_moderation": "Moderação de conteúdo",
        "capture_admin_content_moderation_text_reported_47": "Denunciado",
        "common_search": "Pesquisar",
        "core_settings_actions": "Ações",
        "core_settings_title": "Configurações do sistema",
        "curated_gallery_error_unknown": "Erro desconhecido",
        "dashboard_title": "Painel",
        "enhanced_upload_tags_label": "Tags",
        "event_analytics_revenue": "Receita",
        "event_analytics_total_events": "Total de eventos",
        "event_mod_analytics": "Analytics",
        "event_mod_pending_review": "Pendente de revisão",
        "event_mod_status_label": "Status",
        "events_location": "Localização",
        "messaging_chat_notification_settings_text_notification_settings_2": "Configurações de notificação",
        "messaging_enhanced_messaging_dashboard_text_no_recent_activity": "Sem atividade recente",
        "messaging_media_title": "Mídia",
        "messaging_online_users": "Usuários online",
        "messaging_save_media": "Salvar",
        "search_filter_all": "Todos",
        "settings_bio": "Biografia",
        "settings_enable_email_notifications": "Ativar notificações por e-mail",
        "settings_enable_push_notifications": "Ativar notificações push",
        "settings_security_title": "Configurações de segurança",
        "settings_username": "Nome de usuário",
        "system_settings_account_created": "Conta criada",
        "system_settings_email": "Email",
        "user_dashboard_achievements": "Conquistas",
        "user_dashboard_quick_actions": "Ações rápidas",
        "written_content_upload_description_label": "Descrição",
        "written_content_upload_step_content": "Conteúdo",
        "written_content_upload_step_details": "Detalhes",
        "written_content_upload_title_label": "Título"
    },
    "zh": {
        "admin_admin_payment_text_avg_transaction_4": "平均交易",
        "admin_admin_payment_text_export_selected_36": "导出所选",
        "admin_admin_payment_text_process_refund_2": "处理退款",
        "admin_admin_payment_text_total_refunds_5": "退款总额",
        "admin_admin_payment_text_total_transactions_3": "交易总数",
        "admin_admin_security_center_text_office_network_16": "办公网络",
        "admin_admin_settings_text_content_settings_4": "内容设置",
        "admin_admin_settings_text_danger_zone_9": "危险区域",
        "admin_admin_settings_text_general_settings_2": "常规设置",
        "admin_admin_settings_text_maintenance_settings_8": "维护设置",
        "admin_admin_settings_text_user_settings_3": "用户设置",
        "admin_admin_system_monitoring_text_avg_session_9": "平均会话时长",
        "admin_admin_system_monitoring_text_cpu_usage_1": "CPU 使用率",
        "admin_admin_system_monitoring_text_critical_alerts_5": "关键警报",
        "admin_admin_system_monitoring_text_memory_usage_2": "内存使用",
        "admin_admin_system_monitoring_text_peak_today_8": "今日峰值",
        "admin_admin_system_monitoring_text_response_time_4": "响应时间",
        "admin_admin_system_monitoring_text_warning_alerts_6": "警告提示",
        "admin_admin_user_detail_text_user_details_1": "用户详情",
        "admin_dashboard_active_users": "活跃用户",
        "admin_dashboard_manage_users": "管理用户",
        "admin_dashboard_pending_reviews": "待审核",
        "admin_dashboard_recent_alerts": "最近警报",
        "admin_dashboard_reports": "报告",
        "admin_dashboard_revenue_growth": "收入增长",
        "admin_dashboard_system_health": "系统状态",
        "admin_dashboard_total_users": "用户总数",
        "admin_drawer_menu_admin_settings": "管理员设置",
        "admin_drawer_menu_payments": "支付管理",
        "admin_header_menu_user_management": "用户管理",
        "admin_migration_dialog_run_migration_title": "运行迁移",
        "admin_modern_unified_admin_dashboard_hint_admin_command_center_1": "管理员指令中心",
        "admin_unified_admin_dashboard_text_admin_dashboard_1": "管理员控制台",
        "admin_unified_admin_dashboard_text_view_details_16": "查看详情",
        "ads_ad_report_text_cancel": "取消",
        "ads_my_ads_text_this_action_cannot_4": "此操作无法撤销。",
        "artist_dashboard_recent_activity": "最近活动",
        "artwork_analytics_total_revenue": "总收入",
        "artwork_search_hint": "搜索艺术品...",
        "auth_register_password": "密码",
        "capture_admin_content_moderation_text_content_moderation": "内容审核",
        "capture_admin_content_moderation_text_reported_47": "已举报",
        "common_search": "搜索",
        "core_settings_actions": "操作",
        "core_settings_title": "系统设置",
        "curated_gallery_error_unknown": "未知错误",
        "dashboard_title": "仪表盘",
        "enhanced_upload_tags_label": "标签",
        "event_analytics_revenue": "收入",
        "event_analytics_total_events": "总事件数",
        "event_mod_analytics": "分析",
        "event_mod_pending_review": "待审核",
        "event_mod_status_label": "状态",
        "events_location": "位置",
        "messaging_chat_notification_settings_text_notification_settings_2": "通知设置",
        "messaging_enhanced_messaging_dashboard_text_no_recent_activity": "暂无近期活动",
        "messaging_media_title": "媒体",
        "messaging_online_users": "在线用户",
        "messaging_save_media": "保存媒体",
        "search_filter_all": "全部",
        "settings_bio": "个人简介",
        "settings_enable_email_notifications": "启用电子邮件通知",
        "settings_enable_push_notifications": "启用推送通知",
        "settings_security_title": "安全设置",
        "settings_username": "用户名",
        "system_settings_account_created": "帐户已创建",
        "system_settings_email": "电子邮件",
        "user_dashboard_achievements": "成就",
        "user_dashboard_quick_actions": "快速操作",
        "written_content_upload_description_label": "描述",
        "written_content_upload_step_content": "内容",
        "written_content_upload_step_details": "详细信息",
        "written_content_upload_title_label": "标题"
    }
}


def merge_translations():
    en_data = json.loads(EN_FILE.read_text())
    admin_extraction = json.loads(ADMIN_DATA.read_text())
    # Build mapping from value to key in en.json
    value_to_key = {v: k for k, v in en_data.items()}

    summary = {lang: {"added": [], "updated": [], "errors": []} for lang in TARGET_LANGS}

    # For each translation language, open and update
    for lang in TARGET_LANGS:
        lang_file = TRANSLATIONS_DIR / f"{lang}.json"
        if not lang_file.exists():
            print(f"ERROR: missing: {lang_file}")
            continue
        data = json.loads(lang_file.read_text())
        trans_map = TRANSLATIONS.get(lang, {})

        for key, translated_value in trans_map.items():
            # Validate placeholders
            en_value = en_data.get(key)
            if en_value:
                en_ph = extract_placeholders(en_value)
                tr_ph = extract_placeholders(translated_value)
                if en_ph != tr_ph:
                    summary[lang]["errors"].append({"key": key, "en_ph": list(en_ph), "tr_ph": list(tr_ph)})
            # Merge into lang file: replace if placeholder or missing
            existing = data.get(key)
            if existing is None or (isinstance(existing, str) and existing.strip().startswith("[")):
                data[key] = translated_value
                if existing is None:
                    summary[lang]["added"].append(key)
                else:
                    summary[lang]["updated"].append(key)

        # Write backup and save
        backup = lang_file.with_suffix(lang_file.suffix + ".bak")
        backup.write_text(json.dumps(json.loads(lang_file.read_text()), ensure_ascii=False, indent=2))
        lang_file.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n")

    # Ensure en.json contains keys used by the mapping
    en_added = []
    en_updated = []
    for k in TRANSLATIONS.get('es', {}).keys():
        if k not in en_data:
            # Attempt to find the english string in extraction
            english_string = None
            # Look through admin_extraction files to find the exact text
            for files, items in admin_extraction['files'].items():
                for item in items:
                    # Some values may be truncated; try to match exactly
                    if item['text'] in item['text']:
                        pass
            # Without a direct mapping, create a placeholder English key from the key name
            en_data[k] = "[REVIEW: Missing English text]"
            en_added.append(k)
        else:
            # do not change existing en values
            pass

    if en_added:
        backup = EN_FILE.with_suffix(EN_FILE.suffix + ".bak")
        backup.write_text(json.dumps(json.loads(EN_FILE.read_text()), ensure_ascii=False, indent=2))
        EN_FILE.write_text(json.dumps(en_data, ensure_ascii=False, indent=2) + "\n")

    return {"summary": summary, "en_added": en_added, "en_updated": en_updated}


if __name__ == "__main__":
    print("Merging artbeat_admin translations into assets/translations...")
    res = merge_translations()
    print(json.dumps(res, ensure_ascii=False, indent=2))
