include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    invalid_annotation_target: ignore
    todo: ignore
    deprecated_member_use: ignore # Temporarily ignore deprecated Radio widget warnings
  exclude:
    - "build/**"
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    avoid_print: true
    avoid_unnecessary_containers: true
    avoid_web_libraries_in_flutter: true
    no_logic_in_create_state: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    sized_box_for_whitespace: true
    sort_child_properties_last: true
    use_build_context_synchronously: warning
    use_key_in_widget_constructors: true
    depend_on_referenced_packages: true
    prefer_final_locals: true
    prefer_final_fields: true
    unnecessary_const: true
    unnecessary_new: true
    unnecessary_null_aware_assignments: true
    unnecessary_await_in_return: true
    throw_in_finally: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    file_names: true
    empty_statements: true
    prefer_interpolation_to_compose_strings: true
