# Test configuration for ARTbeat Ads package
# This file configures test behavior and coverage settings

# Test runner configuration
test_runner:
  timeout: 30s
  concurrency: 4
  reporter: expanded

# Coverage configuration
coverage:
  enabled: true
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
    - "**/test/**"
    - "**/examples/**"

# Test categories
categories:
  unit:
    - "test/models/**"
    - "test/services/**"
    - "test/utils/**"

  widget:
    - "test/widgets/**"
    - "test/screens/**"

  integration:
    - "test/integration/**"

# Mock configuration
mocks:
  generate_missing_stubs: true
  fallback_generators: true

# Performance thresholds
performance:
  max_test_duration: 5s
  max_memory_usage: 100MB

# Quality gates
quality:
  min_coverage: 90
  max_complexity: 10
  max_lines_per_test: 100
