name: artbeat_artist
description: Artist and gallery management package for ARTbeat
version: 1.0.0
publish_to: none  # This package is not intended for publishing

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase dependencies - match main project versions
  firebase_core: ^2.32.0
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  firebase_storage: ^11.7.7
  
  # Stripe - updated to match main project
  flutter_stripe: ^11.1.0
  
  # Charts and analytics
  fl_chart: ^0.68.0
  logger: ^2.0.1
  
  # URL launcher for social media links
  url_launcher: ^6.2.2
  
  # Image handling
  image_picker: ^1.0.4
  
  # Cross-package dependency - add artbeat_artwork
  artbeat_artwork:
    path: ../artbeat_artwork
  
  # Local packages
  artbeat_core:
    path: ../artbeat_core
  
  # Other dependencies
  intl: ^0.19.0
  http: ^1.1.0
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.7
  fake_cloud_firestore: ^2.4.4
  http_mock_adapter: ^0.6.1

flutter:
  uses-material-design: true
