name: artbeat_artist
description: Artist and gallery management package for ARTbeat
version: 1.0.1
publish_to: none # This package is not intended for publishing

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase dependencies
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  firebase_storage: ^12.4.7

  # Stripe integration
  flutter_stripe: ^11.1.0

  # Charts and analytics
  fl_chart: ^1.0.0
  logger: ^2.0.2

  # URL launcher for social media links
  url_launcher: ^6.2.5

  # Image handling
  image_picker: ^1.0.7

  # Cross-package dependency
  artbeat_artwork:
    path: ../artbeat_artwork

  # Local packages
  artbeat_core:
    path: ../artbeat_core
  artbeat_events:
    path: ../artbeat_events
  artbeat_ads:
    path: ../artbeat_ads

  # Other dependencies
  intl: ^0.20.2
  http: ^1.2.0
  provider: ^6.1.1

  cached_network_image: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.9

  cloud_firestore_platform_interface: any
flutter:
  uses-material-design: true
